swagger: '2.0'
info:
  version: 1.0.0
  title: Contoh API POST User
  description: Contoh API untuk membuat pengguna baru
host: asia-southeast2-testlogin-366704.cloudfunctions.net
basePath: /postuser
schemes:
  - https
paths:
  /:
    post:
      summary: Membuat Pengguna Baru
      description: API untuk membuat pengguna baru dengan informasi username, password, dan role.
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: user
          description: Informasi pengguna yang akan dibuat
          required: true
          schema:
            type: object
            properties:
              Username:
                type: string
                example: pakrolly
              Password:
                type: string
                example: ganteng
              Role:
                type: string
                example: admin
      responses:
        201:
          description: Pengguna berhasil dibuat
        400:
          description: Permintaan tidak valid
        500:
          description: Kesalahan server
