swagger: "2.0"
info:
  description: "API for managing users"
  version: "1.0.0"
  title: "FANCY PEDIA BACKEND"
host: "your-api-host.com"
basePath: "/api/v1"
schemes:
  - "https"
paths:
  /user/{username}:
    get:
      summary: "Get User by Username"
      description: "Get user information by username"
      parameters:
        - name: "username"
          in: "path"
          required: true
          type: "string"
      responses:
        200:
          description: "User information retrieved successfully"
          schema:
            $ref: "#/definitions/User"
        404:
          description: "User not found"
    delete:
      summary: "Delete User by Username"
      description: "Delete user by username"
      parameters:
        - name: "username"
          in: "path"
          required: true
          type: "string"
      responses:
        204:
          description: "User deleted successfully"
        404:
          description: "User not found"
  /user:
    post:
      summary: "Create User"
      description: "Create a new user"
      parameters:
        - name: "user"
          in: "body"
          description: "User object to be created"
          required: true
          schema:
            $ref: "#/definitions/User"
      responses:
        201:
          description: "User created successfully"
        400:
          description: "Invalid user data"
        409:
          description: "User already exists"
definitions:
  User:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      username:
        type: "string"
      firstName:
        type: "string"
      lastName:
        type: "string"
      email:
        type: "string"
      password:
        type: "string"
    xml:
      name: "User"
